name: Sync gh-pages from main

on:
  schedule:
    # run every 15 minutes (adjust as needed)
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout this branch (gh-pages)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout main into /source
        uses: actions/checkout@v4
        with:
          ref: main
          path: source

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies in main
        run: |
          cd source
          npm ci

      - name: Build site (Tailwind)
        run: |
          cd source
          npm run build

      - name: Deploy built src/ to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./source/src
          destination_branch: gh-pages
          commit_message: "ci: sync from main to gh-pages ({{ github.sha }})"
